### ISSUE TITLE
KDE not Booting and login not fullscreen

### ISSUE THREAD

**Issue by BUCKFAE** [ndugdale/osrs-web-greeter-theme#2] opened 2022-12-17 11:33 UTC
First of all: I really love this project. It is hilarious!

However, i do have issues with selecting KDE:
When i boot up my machine, it shows `plasma` as DE. If i log in, everything works. However, if i click on the button to switch the DE to i3 and then fully turn off the machine, i3 is still selected. If i then click on the toggle again to get back to KDE, i only get the option `Plasma (X11)`. Curiously, if i pick this option and log in, i only get a black screen.
Only way to resolve this was to remove osrs as web-greeter theme, choose dracula, reboot and then choose osrs again. 
Additionally, the login window is not fullscreen for me but rather a small-ish window in the middle with the rest being black.

I am on a fresh install of EndeavorOS and closely followd the steps in the readme. 
The dracula theme works flawless for me.

**Comment by DaLukasTI** [comment] 2022-12-17 17:11
I 2nd this issue. Fresh arch install the login window is there but loging in just gives a black screen, login is also not fullscreen. Above workaround works for me as well

**Comment by ndugdale** [comment] 2022-12-18 13:23
Thanks for the thorough bug report. I’ve been able to recreate your reported behaviour. This is a problem with the codebase. Currently, a LightDMSession.name instead of a LightDMSession.key is being used when launching the desktop session. This only impacts some DEs/WMs, such as Plasma. An attempted quick fix led to some side effects. I hope I will have a stable fix pushed in the next couple of days.

With respect to not being fullscreen, this is by design to mimic the actual Old School RuneScape login which has fixed asset sizes and a black border. However, on HDPI screens this currently may lead to an exaggerated smallness which is undesirable. I’ll create a separate feature request for this. Currently I can’t put a timeframe on when I’ll be able to work on this feature, but please feel free to have a try yourself and make a PR too.

**Comment by BUCKFAE** [comment] 2022-12-18 15:44
Thank you for your quick response and the amount of effort you are putting in this project!
What is the best way to update this on my machine? Full uninstall and then reinstall?
That might be something to add to the readme as well.

**Comment by ndugdale** [comment] 2022-12-19 11:24
No worries! Thanks for checking it out, I've had a lot of fun making this! I have merged a fix for the plasma issue into the main branch. It's been tested on a machine running Arch with bspwm and sowm, as well as a machine running KDE Neon with Plasma (X11) and Plasma (Wayland). Hopefully this means it will work for you too now.

If you still have the git repository cloned locally you can just do the following to upgrade
```
cd <path to local osrs-web-greeter-theme git repository>
npm install
sudo npm run build
```
Otherwise, just follow the 'Installation' steps in the README again. Editing `/etc/lightdm/web-greeter.yml` is only required, if you are currently not using the `osrs` theme.

**Closed** 2022-12-19 11:25 UTC
Labels: bug
